### ISSUE TITLE
apps/perl/5.20.2 binary install error

### ISSUE THREAD

**Issue by vlj91** [alces-software/packager-base#180]
```
alces gridware install perl/5.20.2 --binary --trace
Preparing to install main/apps/perl/5.20.2
Installing main/apps/perl/5.20.2
Importing apps-perl-5.20.2-el7.tar.gz

 > Fetching archive
        Download ... SKIP (Existing source file detected)

 > Preparing import
         Extract ... OK
          Verify ... OK

 > Processing apps/perl/5.20.2/gcc-4.8.5
       Preparing ... OK
       Importing ... /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:184:in `write': Permission denied @ rb_sysopen - /tmp/d20160519-23642-1f7gp7u/el7/pkg/apps/perl/5.20.2/gcc-4.8.5/lib/5.20.2/x86_64-linux/Config.pm (Errno::EACCES)
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:184:in `block (4 levels) in import_package'
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:181:in `each'
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:181:in `block (3 levels) in import_package'
        from /opt/clusterware/lib/ruby/lib/alces/packager/io_handler.rb:145:in `call'
        from /opt/clusterware/lib/ruby/lib/alces/packager/io_handler.rb:145:in `with_spinner'
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:39:in `with_spinner'
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:175:in `block (2 levels) in import_package'
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:137:in `catch'
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:137:in `block in import_package'
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:136:in `each'
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:136:in `import_package'
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:95:in `block in import'
        from /opt/clusterware/opt/ruby/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
        from /opt/clusterware/lib/ruby/lib/alces/packager/archive_importer.rb:73:in `import'
        from /opt/clusterware/lib/ruby/lib/alces/packager/definition_handler.rb:119:in `install_defn'
        from /opt/clusterware/lib/ruby/lib/alces/packager/definition_handler.rb:58:in `install'
        from /opt/clusterware/lib/ruby/lib/alces/packager/definition_handler.rb:31:in `install'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:183:in `block (2 levels) in install'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:216:in `call'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:216:in `with_resource'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:198:in `with_definition'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:182:in `block in install'
        from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/dm-core-1.2.1/lib/dm-core.rb:263:in `block in repository'
        from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/dm-core-1.2.1/lib/dm-core/repository.rb:114:in `scope'
        from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/dm-core-1.2.1/lib/dm-core.rb:263:in `repository'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:223:in `with_depot'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:181:in `install'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:50:in `block in method_missing'
        from /opt/clusterware/opt/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:245:in `block in with_clean_env'
        from /opt/clusterware/opt/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:232:in `with_original_env'
        from /opt/clusterware/opt/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:238:in `with_clean_env'
        from /opt/clusterware/lib/ruby/lib/alces/packager/handler.rb:49:in `method_missing'
        from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:179:in `call'
        from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
        from /opt/clusterware/lib/ruby/vendor/ruby/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from /opt/clusterware/libexec/actions/gridware:75:in `<main>'
```

**Comment by mjtko** [comment]
Urgh. Perl seems to set files as read-only when it installs.  This causes problems for non-root users when the import is executed (root can implicitly modify read-only files, normal users cannot until they update file permissions).

This will cease to be a problem when we resolve alces-software/clusterware#106. For now, the only workaround is to become root to import packages that exhibit this behaviour.

**Comment by mjtko** [comment]
alces-software/clusterware#106 has been fixed and this has been rebuilt/reuploaded.
