### ISSUE TITLE
IPRScan-5.3-46.0 requires Java 1.7

### ISSUE THREAD

**Issue by andrewprovis** [alces-software/packager-base#492]
Running iprscan-5.3.46.0 encounters the following error:

```
[alces@login1(Sonny) ~]$ bash -e -l iprscan.sh 
‘/opt/gridware/depots/349e6902/el7/pkg/apps/iprscan/5.3.46.0/gcc-4.8.5/test/test_proteins.fasta’ -> ‘/home/alces/iprscan/input/test_proteins.fasta’
13/01/2017 17:49:33:305 Welcome to InterProScan-5.3-46.0
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'htmlWriter' defined in class path resource [spring/jobs/outputWriter/html/htmlWriter-context.xml]: Cannot resolve reference to bean 'freeMarkerConfigHtmlWriter' while setting bean property 'freeMarkerConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'freeMarkerConfigHtmlWriter' defined in class path resource [spring/jobs/outputWriter/html/htmlWriter-context.xml]: Initialization of bean failed; nested exception is org.springframework.beans.FatalBeanException: Failed to obtain BeanInfo for class [freemarker.template.Configuration]; nested exception is java.beans.IntrospectionException: type mismatch between read and write methods
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1360)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1118)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:609)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:469)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at uk.ac.ebi.interpro.scan.jms.main.Run.main(Run.java:128)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'freeMarkerConfigHtmlWriter' defined in class path resource [spring/jobs/outputWriter/html/htmlWriter-context.xml]: Initialization of bean failed; nested exception is org.springframework.beans.FatalBeanException: Failed to obtain BeanInfo for class [freemarker.template.Configuration]; nested exception is java.beans.IntrospectionException: type mismatch between read and write methods
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:527)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:322)
	... 15 more
Caused by: org.springframework.beans.FatalBeanException: Failed to obtain BeanInfo for class [freemarker.template.Configuration]; nested exception is java.beans.IntrospectionException: type mismatch between read and write methods
	at org.springframework.beans.CachedIntrospectionResults.<init>(CachedIntrospectionResults.java:262)
	at org.springframework.beans.CachedIntrospectionResults.forClass(CachedIntrospectionResults.java:149)
	at org.springframework.beans.BeanWrapperImpl.getCachedIntrospectionResults(BeanWrapperImpl.java:324)
	at org.springframework.beans.BeanWrapperImpl.getPropertyDescriptors(BeanWrapperImpl.java:331)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.filterPropertyDescriptorsForDependencyCheck(AbstractAutowireCapableBeanFactory.java:1242)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1101)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	... 21 more
Caused by: java.beans.IntrospectionException: type mismatch between read and write methods
	at java.beans.PropertyDescriptor.findPropertyType(PropertyDescriptor.java:661)
	at java.beans.PropertyDescriptor.setReadMethod(PropertyDescriptor.java:257)
	at org.springframework.beans.ExtendedBeanInfo.addOrUpdatePropertyDescriptor(ExtendedBeanInfo.java:282)
	at org.springframework.beans.ExtendedBeanInfo.addOrUpdatePropertyDescriptor(ExtendedBeanInfo.java:180)
	at org.springframework.beans.ExtendedBeanInfo.<init>(ExtendedBeanInfo.java:100)
	at org.springframework.beans.CachedIntrospectionResults.<init>(CachedIntrospectionResults.java:224)
	... 27 more
```

It appears that IPRScan 5.3.46.0 is incompatible with Java 1.8 and requires 1.7 to be set.

Package is available on branch #433

**Comment by andrewprovis** [comment]
This error appears to be caused by the the bundled PRINTS database/binary which is incompatible with CentOS.

This can be fixed by recompiling the binary from the source. However, the instructions for doing so mention that the src is included with the download which it is not for this version (but is with later versions).

**Comment by mjtko** [comment]
Incompatible with CentOS, or incompatible with Java 1.8?  Does everything work if we use Java 1.7 instead?

**Comment by mjtko** [comment]
Looks like we shipped a later version of IPRScan. Closing this as obsolete.
